import { CollectionBrowser } from "@/components/commerce/CollectionBrowser";
import { collections, collectionText } from "@/data/content";
import { Accordion } from "@/components/ui/Accordion";
import { resolveLocale } from "@/lib/i18n-server";
import { notFound } from "next/navigation";
import { Suspense } from "react";

export function generateStaticParams() { return collections.map((collection) => ({ slug: collection.slug })); }

export default async function CollectionPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const locale = await resolveLocale(params);
  const { slug } = await params;
  const source = collections.find((item) => item.slug === slug);
  if (!source) notFound();
  const collection = collectionText(source, locale);
  return <main><section className="collection-hero"><p className="breadcrumbs">{locale === "ru" ? `Главная / Иван-чай / ${collection.name}` : `Home / Ivan Tea / ${collection.name}`}</p><h1>{collection.name}</h1><p>{collection.description} {locale === "ru" ? "Основа каждой смеси — кипрей из Республики Марий Эл." : "Every blend begins with fireweed from the Mari El Republic."}</p><div className="collection-values"><span><b>✦</b>{locale === "ru" ? "Ручной сбор" : "Hand collected"}</span><span><b>◇</b>{locale === "ru" ? "Натуральный состав" : "Natural ingredients"}</span><span><b>0</b>{locale === "ru" ? "Кофеина" : "Caffeine"}</span></div></section><div className="container"><Suspense fallback={<div className="collection-loading">{locale === "ru" ? "Готовим коллекцию…" : "Preparing the collection…"}</div>}><CollectionBrowser initialFlavor={source.filter} locale={locale}/></Suspense></div><section className="collection-editorial container"><p className="eyebrow">{locale === "ru" ? "ЗНАТЬ СВОЙ ЛИСТ" : "KNOW YOUR LEAF"}</p><h2>{locale === "ru" ? `Что отличает коллекцию «${collection.name}»?` : `What makes ${collection.name.toLowerCase()} distinct?`}</h2><div className="editorial-columns"><p>{locale === "ru" ? "Ферментированный кипрей даёт янтарную основу с мягкими нотами сухофруктов. Мы используем крупную нарезку, чтобы лист сохранял собственный характер." : "Fermented fireweed creates an amber base with mellow dried-fruit notes. We use a generous cut so the leaf keeps its own character."}</p><p>{locale === "ru" ? "Фрукты, ягоды, цветки и травы сушатся отдельно и соединяются с чаем только после подготовки. Так каждая добавка остаётся различимой, не перекрывая кипрей." : "Fruit, berries, flowers and herbs are dried separately and combined only after processing. Each addition stays legible without covering the fireweed."}</p></div><div className="faq-list"><Accordion title={locale === "ru" ? "Как заваривать?" : "How should I brew it?"}><p>{locale === "ru" ? "2–3 г на 250 мл, вода 90–95°C, 6–8 минут. Для ягодных смесей можно взять немного больше сухого продукта." : "Use 2–3 g per 250 ml, water at 90–95°C, and steep for 6–8 minutes. Berry blends can take a little more leaf."}</p></Accordion><Accordion title={locale === "ru" ? "Как хранить?" : "How should I store Ivan Tea?"}><p>{locale === "ru" ? "Храните герметично, в сухом месте без прямого солнечного света и сильных запахов, при температуре до 25°C." : "Keep it sealed, dry, away from direct sunlight and strong aromas, at up to 25°C."}</p></Accordion><Accordion title={locale === "ru" ? "Можно купить без розничной упаковки?" : "Is bulk tea available?"}><p>{locale === "ru" ? "Да. Для магазинов, кафе и дистрибьюторов доступны форматы от 1 кг. Свяжитесь с оптовым отделом." : "Yes. Formats from 1 kg are available for shops, cafés and distributors through our wholesale team."}</p></Accordion></div></section></main>;
}
