import Image from "next/image";
import Link from "next/link";
import { localizedHref } from "@/lib/i18n";
import { resolveLocale } from "@/lib/i18n-server";

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const locale = await resolveLocale(params); const ru = locale === "ru";
  return <main className="land-page"><section className="land-hero"><Image src="/images/fedorov/mari-el-landscape.png" alt={ru ? "Поля и леса Республики Марий Эл" : "Fields and forests of the Republic of Mari El"} fill priority sizes="100vw"/><div><span>56.6° N · 47.9° E</span><h1>{ru ? "Марий Эл. Земля между лесом и лугом." : "Mari El. Land between forest and meadow."}</h1></div></section><section className="land-intro"><span>01 · {ru ? "МЕСТО" : "THE PLACE"}</span><h2>{ru ? "Дорога заканчивается задолго до поля." : "The road ends long before the field begins."}</h2><div><p>{ru ? "Марий Эл — небольшая республика к востоку от Волги. Больше половины её территории покрыто лесом; между соснами, берёзами и реками лежат открытые луга, где растёт кипрей." : "Mari El is a small republic east of the Volga. More than half the land is forest; between pine, birch and rivers lie the open meadows where fireweed grows."}</p><p>{ru ? "Мы собираем вдали от трасс, крупных городов и тяжёлой промышленности. Не потому, что это звучит красиво, а потому что чистое место — первая часть рецепта." : "We gather far from highways, large cities and heavy industry. Not because it sounds beautiful, but because a clean place is the first part of the recipe."}</p></div></section><section className="land-panorama"><Image src="/images/fedorov/hero-field.png" alt="" fill sizes="100vw"/><span>{ru ? "ЛЕТО · РУЧНОЙ СБОР" : "SUMMER · GATHERED BY HAND"}</span></section><section className="land-grid"><article><span>02 · {ru ? "ЛАНДШАФТ" : "THE LANDSCAPE"}</span><h2>{ru ? "Лес держит тишину. Луг держит свет." : "The forest holds the quiet. The meadow holds the light."}</h2></article><div><p>{ru ? "Кипрей любит открытые пространства у лесной кромки. Он цветёт ярко, почти вызывающе, среди приглушённых летних трав." : "Fireweed likes open ground at the forest edge. It flowers with almost absurd brightness among the muted summer grasses."}</p><dl><div><dt>{ru ? "Сезон" : "Season"}</dt><dd>{ru ? "Июнь — август" : "June — August"}</dd></div><div><dt>{ru ? "Растение" : "Plant"}</dt><dd>Chamaenerion angustifolium</dd></div><div><dt>{ru ? "Сбор" : "Gathering"}</dt><dd>{ru ? "Вручную" : "By hand"}</dd></div></dl></div></section><section className="people" id="people"><div><Image src="/images/fedorov/organic-campaign.jpg" alt="" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><article><span>03 · {ru ? "ЛЮДИ" : "THE PEOPLE"}</span><h2>{ru ? "Люди, которые знают поле." : "People who know the field."}</h2><p>{ru ? "Небольшая команда собирает и готовит чай. Руки важнее портретов: именно по ним видно внимательность к листу, цветку и каждой партии." : "A small team gathers and makes the tea. Hands matter more than portraits: they show the attention given to each leaf, flower and batch."}</p><Link href={localizedHref(locale, "/craft")}>{ru ? "Как мы делаем чай" : "How we make the tea"} →</Link></article></section></main>;
}
