import { ProductGrid } from "@/components/commerce/ProductGrid";
import { articles } from "@/data/content";
import { products } from "@/data/products";
import Image from "next/image";
import Link from "next/link";

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = articles.find((item) => item.slug === slug) ?? articles[0];
  return <main className="article-page"><header className="article-header container"><p>{article.category} · {article.readTime}</p><h1>{article.title}</h1><span>{article.excerpt}</span><small>WORDS BY THE TEA ROOM · AUGUST 3, 2026</small></header><div className="article-hero-image"><Image src={article.image} alt={article.title} fill priority sizes="100vw"/></div><article className="article-body"><p className="drop-cap">A remarkable cup rarely requires ceremony. It asks only for fresh water, a little attention, and enough room for the leaf to tell you what it has to offer.</p><h2>Begin with good water</h2><p>Tea is mostly water, so the character of that water matters. Fresh, filtered water carries aroma clearly. Water that has been repeatedly boiled tends to taste flat and makes even beautiful leaves feel muted.</p><blockquote>“The best brewing method is the one that makes you want to brew another cup.”</blockquote><h2>Temperature is an ingredient</h2><p>Black and herbal teas welcome water near a full boil. Green and white teas often become sweeter and more dimensional at lower temperatures. If a cup tastes sharp, lower the temperature before shortening the time.</p><div className="article-facts"><div><b>175°F</b><span>Green &amp; white tea</span></div><div><b>195°F</b><span>Oolong tea</span></div><div><b>205°F</b><span>Black &amp; herbal tea</span></div></div><h2>Taste as it opens</h2><p>Steeping times are a starting point, not a verdict. Taste at two minutes, then again at three. You will begin to notice when aroma becomes flavor—and when strength tips into astringency.</p><p>That small practice is the beginning of tea knowledge: not memorizing rules, but learning to pay attention.</p></article><section className="article-products section container"><p className="eyebrow">TEAS FOR PRACTICE</p><h2>Start with a generous leaf</h2><ProductGrid products={products.slice(0, 3)}/></section><nav className="article-next container"><Link href="/blog">← Back to the Field Notes</Link><Link href={`/blog/${articles[1].slug}`}>Next story: {articles[1].title} →</Link></nav></main>;
}
