import Image from "next/image";
import Link from "next/link";
import { localizedHref } from "@/lib/i18n";
import { resolveLocale } from "@/lib/i18n-server";

export default async function CraftPage({ params }: { params: Promise<{ locale: string }> }) {
  const locale = await resolveLocale(params); const ru = locale === "ru"; const steps = ru ? [["01", "Собрать", "Выбираем здоровый лист и оставляем растение жить дальше."], ["02", "Подвялить", "Свежий лист отдыхает, становится мягче и податливее."], ["03", "Скрутить", "Руки раскрывают сок и готовят лист к ферментации."], ["04", "Ферментировать", "Тепло и время переводят зелёный аромат в мягкий фруктовый."], ["05", "Высушить", "Низкая температура сохраняет характер готового листа."]] : [["01", "Gather", "We choose healthy leaves and leave the plant standing."], ["02", "Wither", "Fresh leaves rest until they become soft and pliable."], ["03", "Roll", "Hands release the leaf’s juices and prepare it to ferment."], ["04", "Ferment", "Warmth and time turn green aromas soft and fruit-like."], ["05", "Dry", "Low heat fixes the finished leaf and its character."]];
  return <main className="craft-page"><header className="craft-hero"><span>{ru ? "НАШЕ РЕМЕСЛО" : "OUR CRAFT"}</span><h1>{ru ? "Пять тихих действий между полем и чашкой." : "Five quiet acts between field and cup."}</h1><p>{ru ? "Простая работа требует точности. Каждую небольшую партию ведут по запаху, прикосновению и времени." : "Simple work asks for precision. Each small batch is guided by scent, touch and time."}</p></header><section className="craft-image"><Image src="/images/fedorov/processing-sequence.png" alt={ru ? "Этапы ручной подготовки иван-чая" : "Stages of making Ivan-tea by hand"} fill priority sizes="100vw"/></section><section className="craft-steps">{steps.map(([n, title, text]) => <article key={n}><span>{n}</span><h2>{title}</h2><p>{text}</p></article>)}</section><section className="craft-detail"><div><Image src="/images/fedorov/drying-screens.png" alt="" fill sizes="(max-width: 800px) 100vw, 55vw"/></div><article><span>{ru ? "НЕБОЛЬШИЕ ПАРТИИ" : "SMALL BATCHES"}</span><h2>{ru ? "Не конвейер. Последовательность." : "Not a production line. A sequence."}</h2><p>{ru ? "Температура, влажность и сам лист каждый день немного разные. Поэтому процесс нельзя оставить без внимания. Мы проверяем партию на каждом этапе и смешиваем с отдельно высушенными цветами, травами или ягодами только в конце." : "Temperature, humidity and the leaf itself differ a little each day. The process cannot be left unattended. We check each batch at every stage, adding separately dried flowers, herbs or berries only at the end."}</p><Link href={localizedHref(locale, "/shop")}>{ru ? "Выбрать чай" : "Choose a tea"} →</Link></article></section></main>;
}
